### ISSUE TITLE
How to visualize graph

### ISSUE THREAD

**Issue by SatarupaChak** [mvcisback/py-mdd#1]
Hi @mvcisback ,

I was just trying one of the examples from docs as simple as below

from mdd.nx import to_nx
interface = mdd.Interface(
    inputs={
        "x": [1, 2, 3],
        "y": [6, 23],
        "z": [7, 3, 8],
    },
    output=[-1, 0, 1],
)
func = interface.constantly(-1)
assert func({'x': 1, 'y': 6, 'z': 8}) == -1

graph = to_nx(func)

An error was shown as below and is there any possibility to get the pdf/dot file of the graph?
Traceback (most recent call last):
  File "xxx/newMDD.py", line 16, in <module>
    graph = to_nx(func)
  File "xxx/mdd/nx.py", line 38, in to_nx
    start = bdd2dfa.to_dfa(func.bdd, qdd=False).start
  File "xxx/bdd2dfa/b2d.py", line 88, in to_dfa
    dfa.states()  # Traverses and caches all states.
  File "xxx/funcy/calc.py", line 41, in wrapper
    return memory[key]
  File "<attrs generated hash dfa.dfa.DFA>", line 2, in __hash__
  File "xxx/bdd2dfa/b2d.py", line 29, in __hash__
    return hash(str(self))
  File "xxx/bdd2dfa/b2d.py", line 26, in __str__
    return str(self.ref)
  File "xxx/bdd2dfa/b2d.py", line 22, in ref
    val = self.node.node
AttributeError: 'dd.cudd.Function' object has no attribute 'node'

**Comment by mvcisback** [comment]
Hi @SatarupaChak,

This looks like a problem with my upstream package `bdd2dfa`.

The problem seems to only happen when using the cudd backend. The python backend has no problem.

Should be an easy fix. Will report back later. :)

**Comment by mvcisback** [comment]
@SatarupaChak I updated the latest version of py-mdd `0.3.5` and tested with cudd. As far as I can tell it seems to work.

Please confirm and close the issue if this fixes your problem.

**Comment by SatarupaChak** [comment]
Hi @mvcisback ,

Thanks, it is fixed!.
